### ISSUE TITLE
Inherit from JSTransformer-PostCSS

### ISSUE THREAD

**Issue by RobLoach** [jstransformers/jstransformer-opalcss#1]
https://github.com/jstransformers/jstransformer-postcss

**Comment by tunnckoCore** [comment]
hmm, yea. that's what im thinking to do - update postcss transformer.

**Comment by tunnckoCore** [comment]
@RobLoach is that okey?

**Comment by RobLoach** [comment]
How shall we update jstransformer-postcss?

**Comment by tunnckoCore** [comment]
Mm what? I updated it already. Brings boilerplate to it.

**Comment by RobLoach** [comment]
:+1: https://github.com/jstransformers/jstransformer-opalcss/issues/3
